namespace ClothingStore.Domain.Enumerators
{
    public enum TagEnum
    {
        Sweater,
        Shirt,
        Dress,
        Skirt,
        Poncho,
        Dress_Shoes,
        Sneakers,
        Tennis_shoes,
        V_necks,
        Dress_Shirt,
        Blouse,
        Caps,
        Hats,
        Shorts,
        Jeans,
        Cardigans,
        Boots,
        Jackets,
        Polo_Shirts,
        Pants,
        Coats,
        Blazers,
        Overshirts,
        Hoodies,
        Sweatshirt,
        Colognes,
        Perfumes,
        Accessories
    }
}
